### ISSUE TITLE
Ensure file exists: 'dict object' has no attribute 'diff'

### ISSUE THREAD

**Issue by decentral1se** [weareinteractive/ansible-environment#12]
On latest Ansible, I see:

```
    TASK [franklinkim.environment : Ensure file exists] ****************************                                                             
    fatal: [instance]: FAILED! => {"msg": "The conditional check 'environment_file_result.diff.before.state != \"file\"' failed. The error was: error while evaluating conditi
onal (environment_file_result.diff.before.state != \"file\"): 'dict object' has no attribute 'diff'"} 
```

**Comment by franklinkim** [comment]
Hi, can you provide your playbook?

**Comment by decentral1se** [comment]
Hi, sorry for sparse report but it was the default example playbook from the README. Ansible == 2.6.

**Comment by franklinkim** [comment]
Just ran the test with 2.6.3 and can't see the error: https://travis-ci.org/weareinteractive/ansible-environment/builds/428098662

Do you have any more details about your env?

**Comment by decentral1se** [comment]
Ah, right. I've since not used it and can't remember what I was doing. Perhaps this is a false alarm :)

Thanks for taking some time on this, I'll close off.

**Comment by xescab** [comment]
Hi franklinim,

I'm using Ansible version 2.7.2 and I have the same issue as lwm. Could you please test it? I'm using tests/main.yml palybook.

The error only appears in --check mode. When I actually run the code it works as expected.

Thanks!
