### ISSUE TITLE
default value provided for environment_config not seen as dict

### ISSUE THREAD

**Issue by shanedroid** [weareinteractive/ansible-environment#5]
When invoking this role in internal tests (using docker containers/molecule) for ansible roles I get the following error during playbook runs:

```
TASK [franklinkim.environment : Remove previous values] *******************************
    task path: /ansible/.imported_roles/franklinkim.environment/tasks/config.yml:12
    fatal: [molecule_ubuntu_trusty]: FAILED! => {
        "failed": true,
        "msg": "with_dict expects a dict"
    }
```

Setting a default value fixes this for me, I am not sure why the value parses differently when running playbooks in a docker container as opposed to against a linux host or Vagrant box for it does for me. Curious if anyone else have ever had this issue.

```
environment_config: {}
```

```
11:46 $ ansible --version
ansible 2.3.2.0
  config file = /ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jul 18 2017, 09:16:53) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```
Using version `1.2.3` of this role, example from our `requirements.yml`:

```
- name: franklinkim.environment
  src: git@github.com:weareinteractive/ansible-environment.git
  scm: git
  version: 1.2.3
```

I am running this as a part of testing with a docker container built from [`ubuntu:trusty` ](https://hub.docker.com/_/ubuntu/)

**Comment by franklinkim** [comment]
Hi, odd behaviour... haven't seen this one yet. Thanks for the PR.
