### ISSUE TITLE
ERROR! no action detected in task.

### ISSUE THREAD

**Issue by 00dav00** [weareinteractive/ansible-environment#8]
Hi, I'm trying to use this repo to set some env variables, but I'm getting the following error.

```
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/path-to-dependencies/franklinkim.environment/tasks/main.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- import_tasks: config.yml
  ^ here


The error appears to have been in '/path-to-dependencies/franklinkim.environment/tasks/main.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- import_tasks: config.yml
  ^ here
```

This is code I'm using to install the role:
```
- src: franklinkim.environment
  version: master
  path: dependencies
```

And the code used to include it:
``
  roles:
    - { role: franklinkim.environment, tags: ['env'] }
```


Any idea of what could be happening here?

**Comment by franklinkim** [comment]
what‘s your ansible version?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 00dav00** [comment]
`2.2.1.0`, just saw the version requirement. After updating to `2.4.1` the error changed to:
```
fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "The conditional check 'environment_file_result.diff.before.state != \"file\"' failed. The error was: error while evaluating conditional (environment_file_result.diff.before.state != \"file\"): 'dict object' has no attribute 'diff'"}
```

Which was raised because I wasn't including the role with a `become` statement. The error was rather obscure since when the registered fact does not have the expected attributes and ansible showed this instead of `permission denied` which was showed after commenting `changed_when: environment_file_result.diff.before.state != "file"`

In any case thanks! the version was the source of the problem.
